### ISSUE TITLE
External RAM

### ISSUE THREAD

**Issue by MrSVCD** [MCUdude/MajorCore#18]
Hi,
is there a way to add external ram support to MajorCore?

**Comment by MCUdude** [comment]
There probably _is_ a way, but I'm not going to bother with it. If you really need more RAM I'd just use an ATmega1284 instead.

The ATmega128 also supports external RAM. You can read more about this [here](https://scienceprog.com/adding-external-memory-to-atmega128/).

**Comment by MrSVCD** [comment]
Okay,
I was thinking of ulisp but then I realized that ulisp need at least 32KByte program memory to work.
But having 64KByte for lisp programs would be great using a DIP package.
So it is mostly a pipe dream.
