### ISSUE TITLE
Mistaken Boards Manager URL for MajorCore Install?

### ISSUE THREAD

**Issue by SamWibatt** [MCUdude/MajorCore#19]
Hello, 

the instructions for installing MajorCore with Boards manager give this URL to paste into the Preferences dialog:

> https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json

That didn't seem to add the MajorCore package to boards manager, so I edited it to look like this:

> https://mcudude.github.io/MajorCore/package_MCUdude_MajorCore_index.json

And that made MajorCore visible. 

(BTW thank you so much for these. I have many old AVRs getting new life from them!)

**Comment by MCUdude** [comment]
Wow, I can't believe it has been like this for so long! Thanks for reporting 🙂
