### ISSUE TITLE
Pin change interrupts... PCICR?

### ISSUE THREAD

**Issue by emolatur** [MCUdude/MajorCore#24]
There's a 100% chance I'm missing something, but the steps for using PC interrupts on arduino projects cannot be applied using majorcore because "'PCICR' was not declared in this scope"

**Comment by MCUdude** [comment]
It depends on your target. ATmega8515 does not support PCINT's at all. ATmega162 has PCINT on some pins, but the register names may be slightly different. Look it up in the ATmega162 datasheet, and  the [iom162.h](https://github.com/vancegroup-mirrors/avr-libc/blob/master/avr-libc/include/avr/iom162.h) definition file.
